(defpackage main
  (:use :common-lisp :dimension
        :algebra :poly-io :external-helpers :find-statistical-fan :experimental-design
        #+cmu :ext
        #+sbcl :sb-ext))

(in-package main)
(defvar *count*)
(defvar *gfan*)
(defvar *gfan-leading-terms*)

(defun leading-terms (polys)
  (sort (mapcar #'cdar polys) #'lex-less))

(defun on-sequence (seq polys)
  (when (zerop *count*)
    (format t "Groebner basis:~%")
    (dolist (poly polys)
      (format t "  ")
      (poly-print poly)
      (format t "~%"))
    (format t "~%Groebner fan consists of...")
    (setf *gfan* (get-gfan polys))
    (setf *gfan-leading-terms* nil)
    (format t " ~a bases~%" (length *gfan*))
    (dolist (polys *gfan*)
      (push (leading-terms polys) *gfan-leading-terms*))
    (format t "~%"))
  (format t "(")
  (setf seq (reverse seq))
  (dolist (monom seq)
    (unless (equalp monom (car seq))
      (format t ", "))
    (term-print (cons 1 monom)))
  (format t ")~%")
  (unless (find (leading-terms polys) *gfan-leading-terms* :test #'equalp)
    (format t "  (not in algebraic fan)~%"))
  (incf *count*))

(defun run-test (caller)
  (format t "~a~%" caller)
  (let ((*count* 0))
    (eval caller)
    (format t "Found ~a models~%" *count*)))

(defun test ()
  (let ((poly-io:*vars* '("x" "y" "z" "w" "p" "q"))
        (*on-sequence* #'on-sequence))
    (setf find-statistical-fan:*use-symmetry* t)
    (setf find-statistical-fan:*use-coordinate-repetitions* t)
    (setf *vars* (subseq *vars* 0 4))
    (run-test '(find-fan (cube 4)))
    (setf *vars* (subseq *vars* 0 3))
    (run-test '(find-fan (cube 3)))
    (run-test '(find-fan (box-behnken 3)))
    (run-test '(find-fan (box-wilson-ccc 3)))
    (setf *vars* (subseq *vars* 0 2))
    (run-test '(find-fan (cube 2)))
    (run-test '(find-fan (box-behnken 2)))
    (run-test '(find-fan (box-wilson-ccc 2)))
    ))

(defun test-to-file (filename)
  (with-open-file (*standard-output* filename :direction :output :if-exists :supersede)
    (test)))

(defun main ()
  (let ((poly-io:*vars* '("x" "y" "z" "w" "p" "q"))
        (*on-sequence* #'on-sequence))
    (setf *vars* (subseq *vars* 0 4))
    (setf find-statistical-fan:*use-symmetry* t)
    ;(run-test '(find-fan (box-wilson-ccf 3)))
    (run-test '(find-fan (box-behnken 4)))
    ))
